实现`Promise.all`方法，该方法接收一个可迭代集合作为参数，当集合中有任何一个`promise`的状态为`rejected`的时候，则修改整个`promise`的状态；如果全部`promise`的状态都为`fulfilled`的时候，则返回数组，数组元素的值对应了`promise`执行的结果

```javascript
Promise._all = function(iterObj) {
  if(!(typeof iterObj === 'object' && iterObj !== null && typeof iterObj[Symbol.iterator] === 'function')) {
    throw new TypeError('error')
  }
  let n = iterObj.length
  let results = new Array(n)  // 执行结果
  let cnt = 0  // 成功个数
  
  return new Promise((resolve, reject) => {
    if(n === 0) resolve([])
    iterObj.forEach(async (item,index) => {
      try {
        let res = await item  // 获取promise执行结果
        // 保存到results中
        results[index] = res
        if(++cnt === n) {  // 全部都成功
          resolve(results)  // 调用resolve
        }
      } catch(err) {
        reject(err)
      }
    })
  })
}
```

写法二：

```javascript
Promise._all = function(promises) {
  return new Promise((resolve, reject) => {
    let cnt = 0, n = promises.length
    let results = []
    promises.forEach((item, idx) => {
      Promise.resolve(item).then(res => {
        results.push(res)
        if(++cnt === n) resolve(results)
      }).catch(reject)
    })
  })
}
```

写法三

```javascript
Promise.all = function(promises) {
  let data = [], cnt = 0
  const saveData = (i, res, resolve) => {
    data[i] = res
    cnt ++
    if(cnt === promises.length) {
      resolve(data)
    }
  }
  return new Promise((resolve, reject) => {
    if(!Array.isArray(promises)) reject("type error")
    for(let i = 0; i < promises.length; i ++) {
      promises[i].then((res) => {
        saveData(i, res, resolve)
      }).catch((err) => {
        reject(err)
      })
    }
  })
}

// 测试
let task = (time, res, type='resolve') => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (type === 'resolve') {
        resolve(res)
      } else {
        reject(res)
      }
    }, time);
  })
}
let p1 = task(500, 1)
let p2 = task(1000, 2, 'reject')
let p3 = task(1500, 3)
Promise.all([p1,p2,p3]).then((res) => {
  console.log(res);
}).catch(err => {
  console.log(err);
})
```

