Promise.retry 超时重新请求，并在重试一定次数依然失败时输出缓存内容

```javascript
Promise.retry = (callback, retryTime) => {
  // 返回一个新的promise
  return new Promise((resolve, reject) => {
    // 执行回调函数 如果成功直接resolve
    callback().then(res => {
      resolve(res)
    }, (err) => {  // 失败
      --retryTime  // 次数减少
      // 判断剩余次数 是否为0
      // 如果为0 则reject失败原因
      if(retryTime == 0) reject(err)
      // 还有次数 递归调用
      else Promise.retry(callback, retryTime
).then(resolve, reject)
    })
  })
}

let count = 1
// 只能试错两次 如果超过2次则返回fail
Promise.retry(() => {
  return count ++ == 3 ? Promise.resolve('success') : Promise.reject('fail')
}, 2).then(res => console.log(res))
```

写法二：

```javascript
// promise 执行任务
// wait等待下次执行时间
// time执行次数
Promise.retry = function(promise, wait, time) {
  return new Promise((resolve, reject) => {
		let executor = () => {
      // 执行promise任务 then函数成功表示执行成功
			promise().then((res) => {
				resolve(res)
			}).catch((err) => {
        time --  // 次数减少
        if(time === 0) {  // 可用次数为0
          reject(err)  // 调用reject
        } else {
          // 重新调用
          setTimeout(executor, wait)
        }
      })
		}
  })
}

(() => {
  const fetchData = () => {
    // 返回一个 Promise 对象，表示异步请求数据
    return fetch('http://example.com/data')
  };

  console.log(fetchData());

  Promise.retry(fetchData, 1000, 3, '缓存内容')
    .then((data) => {
      // 成功获取数据
      console.log(data);
    })
    .catch((error) => {
      // 请求失败或超时，并且重试多次依然失败
      console.error(error);
    });
})()
```

